# Generated by Django 4.2.4 on 2023-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_openhours_break_end_time_openhours_break_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_detail',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='menu_detail_content'),
        ),
        migrations.AlterField(
            model_name='menu_detail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
