# Generated by Django 4.2.4 on 2023-08-13 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes_restaurant',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.likes'),
        ),
        migrations.AddField(
            model_name='likes_restaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
        ),
    ]
