# Generated by Django 4.2.4 on 2023-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_1',
            field=models.ImageField(null=True, upload_to='reviews/review-img'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_2',
            field=models.ImageField(null=True, upload_to='reviews/review-img'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_3',
            field=models.ImageField(null=True, upload_to='reviews/review-img'),
        ),
    ]
