# Generated by Django 4.2.4 on 2023-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_alter_review_image_1_alter_review_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes_restaurant',
            name='like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
