# Generated by Django 4.2.4 on 2023-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_likes_restaurant_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes_restaurant',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='review',
            name='koogle',
            field=models.IntegerField(default=0, verbose_name='koogle'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=0, verbose_name='star'),
        ),
    ]
